=== PssbleTrngle/Dungeon/src/main/resources/data/dungeon/palettes/palette.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema id="palette" elementFormDefault="qualified" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="palette" type="palette" />

	<xs:simpleType name="type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="floor" />
			<xs:enumeration value="wall" />
			<xs:enumeration value="path" />
			<xs:enumeration value="rune" />
			<xs:enumeration value="gem" />
			<xs:enumeration value="seal" />
			<xs:enumeration value="glass" />
			<xs:enumeration value="falling" />
			<xs:enumeration value="pillar" />
			<xs:enumeration value="lamp" />
			<xs:enumeration value="stairs" />
			<xs:enumeration value="slab" />
			<xs:enumeration value="stairs_wall" />
			<xs:enumeration value="slab_wall" />
			<xs:enumeration value="planks" />
			<xs:enumeration value="stairs_wood" />
			<xs:enumeration value="slab_wood" />
			<xs:enumeration value="leaves" />
			<xs:enumeration value="stripped_log" />
			<xs:enumeration value="log" />
			<xs:enumeration value="dirt" />
			<xs:enumeration value="grass" />
			<xs:enumeration value="farmland" />
			<xs:enumeration value="plant" />
			<xs:enumeration value="crop" />
			<xs:enumeration value="fruit" />
			<xs:enumeration value="bookshelf" />
			<xs:enumeration value="fence" />
			<xs:enumeration value="wall_block" />
			<xs:enumeration value="fluid_unsafe" />
			<xs:enumeration value="pressure_plate" />
			<xs:enumeration value="button" />
			<xs:enumeration value="lever" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="weighted">
		<xs:attribute use="optional" type="xs:float" name="weight" default="1" />
	</xs:complexType>

	<xs:complexType name="name">
		<xs:complexContent>
			<xs:extension base="weighted">
				<xs:attribute use="optional" default="minecraft" name="mod" type="xs:string" />
				<xs:attribute use="required" name="id" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="provider" abstract="true" />
	<xs:complexType name="provider">
		<xs:complexContent>
			<xs:extension base="weighted">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" ref="property" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="palette">
		<xs:complexContent>
			<xs:extension base="weighted">
				<xs:sequence>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" minOccurs="0" name="replace" type="replace" />
					</xs:sequence>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" minOccurs="0" name="mob" type="name" />
					</xs:sequence>
				</xs:sequence>
				<xs:attribute use="required" name="name" type="xs:string" />
				<xs:attribute use="required" name="biome" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="replace">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1" name="type" type="type" />
			<xs:element ref="provider" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="property" abstract="true" />

	<xs:element name="set" substitutionGroup="property">
		<xs:complexType>
			<xs:attribute use="required" name="key" type="xs:string" />
			<xs:attribute use="required" name="value">
				<xs:simpleType>
					<xs:union memberTypes="xs:float xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="cycle" substitutionGroup="property">
		<xs:complexType>
			<xs:attribute use="required" name="key" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="block" substitutionGroup="provider">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="provider">
					<xs:attribute use="optional" default="minecraft" name="mod" type="xs:string" />
					<xs:attribute use="required" name="id" type="xs:string" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="tag" substitutionGroup="provider">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="provider">
					<xs:attribute use="required" name="id" type="xs:string" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="collection" substitutionGroup="provider">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="provider">
					<xs:sequence>
						<xs:element maxOccurs="unbounded" minOccurs="1" ref="provider" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="variant" substitutionGroup="provider">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="provider">
					<xs:sequence>
						<xs:element maxOccurs="32" minOccurs="1" ref="provider" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="fallback" substitutionGroup="provider">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="provider">
					<xs:sequence>
						<xs:element maxOccurs="unbounded" minOccurs="1" ref="provider" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="ref" substitutionGroup="provider">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="provider">
					<xs:attribute use="required" name="to" type="type" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== PssbleTrngle/Dungeon/src/main/resources/data/dungeon/palettes/mushroom.xml
<?xml version="1.0" encoding="UTF-8" ?>
<palette weight="1" biome="mushroom_fields" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.w3schools.com" xsi:schemaLocation="https://www.w3schools.com palette.xsd">
    <replace>
        <type>grass</type>
        <block id="mycelium" />
    </replace>
    <replace>
        <type>leaves</type>
        <variant>
            <block id="red_mushroom_block" />
            <block id="brown_mushroom_block" />
        </variant>
    </replace>
    <replace>
        <type>log</type>
        <block id="mushroom_stem" />
    </replace>
    <replace>
        <type>plant</type>
        <collection>
            <block id="red_mushroom" />
            <block id="brown_mushroom" />
        </collection>
    </replace>
</palette>

=== PssbleTrngle/Dungeon/src/main/resources/data/dungeon/palettes/stone.xml
<?xml version="1.0" encoding="UTF-8" ?>
<palette name="stone" weight="1" biome="plains" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="palette.xsd">
	<replace>
		<type>floor</type>
		<type>pillar</type>
		<collection>
			<block id="stone" weight="1" />
			<block id="andesite" weight="0.7" />
		</collection>
	</replace>
	<replace>
		<type>path</type>
		<block id="cobblestone" />
	</replace>
	<replace>
		<type>wall</type>
		<collection>
			<block weight="1" id="stone_bricks" />
			<block weight="0.1" id="mossy_stone_bricks" />
			<block weight="0.1" id="cracked_stone_bricks" />
		</collection>
	</replace>
	<replace>
		<type>gem</type>
		<collection>
			<block weight="1.5" id="diamond_block" />
			<block weight="1.5" id="gold_block" />
			<block weight="1" id="emerald_block" />
			<block weight="0.1" id="lapis_block" />
		</collection>
	</replace>
	<replace>
		<type>rune</type>
		<block id="chiseled_stone_bricks" />
	</replace>
	<replace>
		<type>lamp</type>
		<block id="redstone_lamp" />
	</replace>
	<replace>
		<type>slab</type>
		<block id="stone_slab" />
	</replace>
	<replace>
		<type>stairs</type>
		<block id="stone_stairs" />
	</replace>
	<replace>
		<type>slab_wall</type>
		<collection>
			<block weight="1" id="stone_brick_slab" />
			<block weight="0.1" id="mossy_stone_brick_slab" />
		</collection>
	</replace>
	<replace>
		<type>stairs_wall</type>
		<collection>
			<block weight="1" id="stone_brick_stairs" />
			<block weight="0.1" id="mossy_stone_brick_stairs" />
		</collection>
	</replace>
	<replace>
		<type>grass</type>
		<block id="grass_block" />
	</replace>
	<replace>
		<type>glass</type>
		<block id="glass" />
	</replace>
	<replace>
		<type>falling</type>
		<block id="gravel" />
	</replace>
	<replace>
		<type>planks</type>
		<variant>
			<block id="oak_planks" />
			<block id="spruce_planks" />
			<block id="dark_oak_planks" />
		</variant>
	</replace>
	<replace>
		<type>stairs_wood</type>
		<variant>
			<block id="oak_stairs" />
			<block id="spruce_stairs" />
			<block id="dark_oak_stairs" />
		</variant>
	</replace>
	<replace>
		<type>slab_wood</type>
		<variant>
			<block id="oak_slab" />
			<block id="spruce_slab" />
			<block id="dark_oak_slab" />
		</variant>
	</replace>
	<replace>
		<type>log</type>
		<variant>
			<block id="oak_log" />
			<block id="spruce_log" />
			<block id="dark_oak_log" />
		</variant>
	</replace>
	<replace>
		<type>stripped_log</type>
		<variant>
			<block id="stripped_oak_log" />
			<block id="stripped_spruce_log" />
			<block id="stripped_dark_oak_log" />
		</variant>
	</replace>
	<replace>
		<type>leaves</type>
		<variant>
			<block id="oak_leaves" />
			<block id="spruce_leaves" />
			<block id="dark_oak_leaves" />
		</variant>
	</replace>
	<replace>
		<type>crop</type>
		<variant>
			<cycle key="age" />
			<block id="wheat" />
			<block id="potatoes" />
			<block id="carrots" />
			<block id="beetroots" />
		</variant>
	</replace>
	<replace>
		<type>fence</type>
		<variant>
			<block id="oak_fence" />
			<block id="spruce_fence" />
			<block id="dark_oak_fence" />
		</variant>
	</replace>
	<replace>
		<type>farmland</type>
		<block id="farmland" />
	</replace>
	<replace>
		<type>dirt</type>
		<block id="dirt" />
	</replace>
	<replace>
		<type>pressure_plate</type>
		<block id="stone_pressure_plate" />
	</replace>
	<replace>
		<type>fluid_unsafe</type>
		<block id="lava" />
	</replace>
	<replace>
		<type>wall_block</type>
		<block id="stone_brick_wall" />
	</replace>
	<replace>
		<type>lever</type>
		<block id="lever" />
	</replace>
	<replace>
		<type>button</type>
		<block id="stone_button" />
	</replace>
	<replace>
		<type>wall_block</type>
		<block id="stone_brick_wall" />
	</replace>
	<replace>
		<type>plant</type>
		<collection>
			<block id="dandelion" />
			<block id="poppy" />
			<block id="blue_orchid" />
			<block id="azure_bluet" />
		</collection>
	</replace>
	<replace>
		<type>fruit</type>
		<variant>
			<block id="melon" />
			<block id="pumpkin" />
		</variant>
	</replace>
	<replace>
		<type>seal</type>
		<block id="polished_andesite" />
	</replace>
	<replace>
		<type>bookshelf</type>
		<block id="bookshelf" />
	</replace>
	<mob weight="1" id="zombie" />
	<mob weight="0.1" id="creeper" />
</palette>

=== PssbleTrngle/Dungeon/src/main/resources/data/dungeon/palettes/sand.xml
<?xml version="1.0" encoding="UTF-8" ?>
<palette weight="1" biome="desert" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.w3schools.com" xsi:schemaLocation="https://www.w3schools.com palette.xsd">
    <replace>
        <type>floor</type>
        <block id="sandstone" />
    </replace>
    <replace>
        <type>wall</type>
        <type>pillar</type>
        <block id="smooth_sandstone" />
    </replace>
    <replace>
        <type>rune</type>
        <block id="chiseled_sandstone" />
    </replace>
    <replace>
        <type>path</type>
        <type>falling</type>
        <type>farmland</type>
        <block id="sand" />
    </replace>
    <replace>
        <type>grass</type>
        <block id="dirt" />
    </replace>
    <replace>
        <type>slab</type>
        <type>slab_wall</type>
        <block id="sandstone_slab" />
    </replace>
    <replace>
        <type>stairs</type>
        <type>stairs_wall</type>
        <block id="sandstone_stairs" />
    </replace>
    <replace>
        <type>wall_block</type>
        <block id="sandstone_wall" />
    </replace>
    <replace>
        <type>fence</type>
        <block id="acacia_fence" />
    </replace>
    <replace>
        <type>planks</type>
        <block id="acacia_planks" />
    </replace>
    <replace>
        <type>log</type>
        <block id="acacia_log" />
    </replace>
    <replace>
        <type>leaves</type>
        <block id="acacia_leaves" />
    </replace>
    <replace>
        <type>stairs_wood</type>
        <block id="acacia_stairs" />
    </replace>
    <replace>
        <type>slab_wood</type>
        <block id="acacia_slab" />
    </replace>
    <replace>
        <type>crop</type>
        <type>plant</type>
        <collection>
            <block weight="1" id="dead_bush" />
            <block weight="0.2" id="cactus" />
        </collection>
    </replace>
    <replace>
        <type>fruit</type>
        <block id="melon" />
    </replace>
    <replace>
        <type>gem</type>
        <collection>
            <block id="gold_block" />
            <block id="coal_block" />
            <block id="lapis_block" />
        </collection>
    </replace>
    <mob weight="1" id="husk" />
    <mob weight="0.3" id="skeleton" />
</palette>

=== PssbleTrngle/Dungeon/src/main/resources/data/dungeon/palettes/nature.xml
<?xml version="1.0" encoding="UTF-8" ?>
<palette weight="1" biome="nether" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.w3schools.com" xsi:schemaLocation="https://www.w3schools.com palette.xsd">
    <replace>
        <type>floor</type>
        <collection>
            <block id="stone" weight="1" />
            <block id="mossy_cobblestone" weight="0.5" />
        </collection>
    </replace>
    <replace>
        <type>pillar</type>
        <variant>
            <block id="dark_oak_log"></block>
            <block id="spruce_log"></block>
            <block id="jungle_log"></block>
            <block id="oak_log"></block>
        </variant>
    </replace>
    <replace>
        <type>path</type>
        <collection>
            <block weight="1" id="grass_path" />
            <block weight="1" id="dirt" />
            <block weight="1" id="coarse_dirt" />
        </collection>
    </replace>
    <replace>
        <type>wall</type>
        <collection>
            <block weight="1" id="stone_bricks" />
            <block weight="0.8" id="mossy_stone_bricks" />
            <block weight="0.6" id="cracked_stone_bricks" />
        </collection>
    </replace>
    <replace>
        <type>gem</type>
        <collection>
			<block weight="2" id="emerald_block" />
			<block weight="1" id="gold_block" />
        </collection>
    </replace>
    <mob weight="1" id="cave_spider" />
</palette>

=== PssbleTrngle/Dungeon/src/main/resources/data/dungeon/palettes/end.xml
<?xml version="1.0" encoding="UTF-8" ?>
<palette weight="1" biome="end" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.w3schools.com" xsi:schemaLocation="https://www.w3schools.com palette.xsd">
    <dimensions type="whitelist">
        <entry>minecraft:the_end</entry>
    </dimensions>
    <replace>
        <type>floor</type>
        <block id="end_stone" />
    </replace>
    <replace>
        <type>path</type>
        <block id="end_stone_bricks" />
    </replace>
    <replace>
        <type>wall</type>
        <block id="purpur_block" />
    </replace>
    <replace>
        <type>pillar</type>
        <block id="purpur_pillar" />
    </replace>
    <replace>
        <type>gem</type>
        <block id="obsidian" />
    </replace>
    <replace>
        <type>stairs</type>
        <block id="end_stone_brick_stairs" />
    </replace>
    <replace>
        <type>slab</type>
        <block id="end_stone_brick_slab" />
    </replace>
    <replace>
        <type>stairs_wall</type>
        <block id="purpur_stairs" />
    </replace>
    <replace>
        <type>slab_wall</type>
        <block id="purpur_slab" />
    </replace>
    <replace>
        <type>falling</type>
        <block id="black_concrete_powder" />
    </replace>
    <replace>
        <type>crop</type>
        <block id="air" />
    </replace>
    <replace>
        <type>glass</type>
        <block id="purple_stained_glass" />
    </replace>
    <replace>
        <type>wall_block</type>
        <block id="end_stone_brick_wall" />
    </replace>
    <mob weight="1" id="shulker" />
    <mob weight="0.5" id="endermite" />
    <mob weight="0.1" id="enderman" />
</palette>

=== PssbleTrngle/Dungeon/src/main/resources/data/dungeon/palettes/prismarine.xml
<?xml version="1.0" encoding="UTF-8" ?>
<palette weight="1" biome="ocean" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.w3schools.com" xsi:schemaLocation="https://www.w3schools.com palette.xsd">
    <replace>
        <type>floor</type>
        <block id="prismarine" />
    </replace>
    <replace>
        <type>path</type>
        <type>pillar</type>
        <block id="dark_prismarine" />
    </replace>
    <replace>
        <type>lamp</type>
        <block id="sea_lantern" />
    </replace>
    <replace>
        <type>wall</type>
        <block id="prismarine_bricks" />
    </replace>
    <replace>
        <type>gem</type>
        <collection>
            <block id="gold_block" />
            <block id="lapis_block" />
        </collection>
    </replace>
    <replace>
        <type>stairs</type>
        <block id="prismarine_stairs" />
    </replace>
    <replace>
        <type>slab</type>
        <block id="prismarine_slab" />
    </replace>
    <replace>
        <type>stairs_wall</type>
        <block id="prismarine_brick_stairs" />
    </replace>
    <replace>
        <type>slab_wall</type>
        <block id="prismarine_brick_slab" />
    </replace>
    <replace>
        <type>farmland</type>
        <type>dirt</type>
        <type>grass</type>
        <type>falling</type>
        <block id="sand" />
    </replace>
    <replace>
        <type>fruit</type>
        <collection>
            <block id="wet_sponge" />
            <tag weight="0.2" id="#coral_blocks"></tag>
        </collection>
    </replace>
    <replace>
        <type>crop</type>
        <block id="sugar_cane" />
    </replace>
    <replace>
        <type>wall_block</type>
        <block id="prismarine_wall" />
    </replace>
    <replace>
        <type>plant</type>
        <tag id="#corals">
            <set key="waterlogged" value="false" />
        </tag>
    </replace>
</palette>

=== PssbleTrngle/Dungeon/src/main/resources/data/dungeon/palettes/nether.xml
<?xml version="1.0" encoding="UTF-8" ?>
<palette weight="1" biome="nether" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.w3schools.com" xsi:schemaLocation="https://www.w3schools.com palette.xsd">
    <replace>
        <type>floor</type>
        <collection>
            <block id="netherrack" weight="1" />
            <block id="soul_sand" weight="0.1" />
        </collection>
    </replace>
    <replace>
        <type>path</type>
        <collection>
            <block weight="1" id="soul_sand" />
            <block weight="3" id="gravel" />
        </collection>
    </replace>
    <replace>
        <type>wall</type>
        <type>pillar</type>
        <collection>
            <block weight="1" id="nether_bricks" />
            <block weight="0.2" id="red_nether_bricks" />
        </collection>
    </replace>
    <replace>
        <type>gem</type>
        <collection>
            <block weight="2" id="gold_block" />
            <block weight="1" id="obsidian" />
            <block weight="1" id="quartz_block" />
        </collection>
    </replace>
    <replace>
        <type>rune</type>
        <block id="magma_block" />
    </replace>
    <replace>
        <type>fruit</type>
        <variant>
            <block id="nether_wart_block" />
            <block id="pumpkin" />
        </variant>
    </replace>
    <replace>
        <type>lamp</type>
        <block id="glowstone" />
    </replace>
    <replace>
        <type>glass</type>
        <block id="red_stained_glass" />
    </replace>
    <replace>
        <type>stairs</type>
        <type>stairs_wall</type>
        <block id="nether_brick_stairs" />
    </replace>
    <replace>
        <type>slab</type>
        <type>slab_wall</type>
        <block id="nether_brick_slab" />
    </replace>
    <replace>
        <type>crop</type>
        <block id="nether_wart">
            <cycle key="age" />
        </block>
    </replace>
    <replace>
        <type>falling</type>
        <block id="red_concrete_powder" />
    </replace>
    <replace>
        <type>leaves</type>
        <variant>
            <block id="red_mushroom_block" />
            <block id="brown_mushroom_block" />
        </variant>
    </replace>
    <replace>
        <type>log</type>
        <block id="mushroom_stem" />
    </replace>
    <replace>
        <type>plant</type>
        <collection>
            <block id="red_mushroom" />
            <block id="brown_mushroom" />
        </collection>
    </replace>
    <replace>
        <type>wall</type>
        <block id="nether_brick_wall" />
    </replace>
    <replace>
        <type>fence</type>
        <block id="nether_brick_fence" />
    </replace>
    <replace>
        <type>farmland</type>
        <block id="soul_sand" />
    </replace>
    <mob weight="1" id="cave_spider" />
</palette>

=== PssbleTrngle/Dungeon/src/main/resources/data/dungeon/palettes/quartz.xml
<?xml version="1.0" encoding="UTF-8" ?>
<palette weight="1" biome="plains" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.w3schools.com" xsi:schemaLocation="https://www.w3schools.com palette.xsd">
    <replace>
        <type>wall</type>
        <type>floor</type>
        <block id="quartz_block" />
    </replace>
    <replace>
        <type>pillar</type>
        <block id="quartz_pillar" />
    </replace>
    <replace>
        <type>rune</type>
        <type>path</type>
        <block id="chiseled_quartz_block" />
    </replace>
    <replace>
        <type>slab</type>
        <type>slab_wall</type>
        <block id="quartz_slab" />
    </replace>
    <replace>
        <type>stairs</type>
        <type>stairs_wall</type>
        <block id="quartz_stairs" />
    </replace>
    <replace>
        <type>gem</type>
        <collection>
            <block id="gold_block" />
            <block id="diamond_block" />
        </collection>
    </replace>
    <replace>
        <type>falling</type>
        <block id="white_concrete_powder" />
    </replace>
    <replace>
        <type>lamp</type>
        <block id="glowstone" />
    </replace>
</palette>
